[package]
name = "belene"
description = "Belene provides little endian and big endian versions of the basic integral types."
version = "0.2.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"

[dependencies]
